### ISSUE TITLE
[BUG] user status in services setting shows error regardless of their status

### ISSUE THREAD

**Issue by khodedawsh** [khodedawsh/marzneshin#330] opened 2024-05-30 11:49 UTC
![image](https://github.com/khodedawsh/marzneshin/assets/156741006/5d41780d-4820-4515-9164-239415ba6607)

- [x] fix: services setting page title translation
- [ ] #351
- [ ] error status of user

**Comment by khodedawsh** [comment] 2024-05-30 11:50
also note the extra s in translation

**Comment by Krr0ptioN** [comment] 2024-05-31 18:17
I'll delegate this to coming week iteration, 7 iteration

**Comment by Krr0ptioN** [comment] 2024-06-01 21:12
![image](https://github.com/khodedawsh/marzneshin/assets/54506351/629d1cc5-b684-4ddb-a795-d8d947fd8ffc)

Contrary to what was expected, the issue is that `GET /api/service/:id` API endpoint response does not include `status` in users array field.

**Comment by Krr0ptioN** [comment] 2024-06-01 21:15
@khodedawsh I'll reassign it to urslf.

**Closed** 2024-06-07 23:10 UTC
Labels: bug, backend
