### ISSUE TITLE
[BUG] translation for node connection backend isn't working or is absent

### ISSUE THREAD

**Issue by khodedawsh** [khodedawsh/marzneshin#331] opened 2024-05-30 11:53 UTC
![image](https://github.com/khodedawsh/marzneshin/assets/156741006/2df1776d-163a-4c1b-8640-0c7420807382)

**Comment by Krr0ptioN** [comment] 2024-06-06 20:34
![image](https://github.com/khodedawsh/marzneshin/assets/54506351/9178ef1b-3b62-43bb-a2fe-c4b7eb970a73)

- The translation does exist.
- I was not able to reproduce this. 

Closing until further occurrence.

**Closed by Krr0ptioN** 2024-06-06 20:34 UTC
Labels: bug, uncertain
