### ISSUE TITLE
[BUG] xray config is sometimes empty and only shows []

### ISSUE THREAD

**Issue by khodedawsh** [khodedawsh/marzneshin#328] opened 2024-05-30 11:42 UTC
when loading xray config for the first time (often on a remote server) the config is empty and only contains []

**Comment by Krr0ptioN** [comment] 2024-05-30 11:46
Is it temporary or stay the same when you refresh the page? Does closing the settings window and reopening it again, resolves glitch?

**Comment by khodedawsh** [comment] 2024-05-30 11:47
it gets fixed after reopening the sheet. no need to even refresh the page.

**Comment by Krr0ptioN** [comment] 2024-05-31 18:24
I'll delegate this to 7 iteration.

**Comment by Krr0ptioN** [comment] 2024-06-01 21:40
I was unable to reproduce this issue.

**Closed** 2024-06-08 14:45 UTC
Labels: bug, frontend
